lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
If the first, say, 16 digits of a 23 digit number are a valid credit card number, we currently redact the number. But we probably should not. If the entire number has a prefix which is a valid-looking credit card number, it still is unlikely to actually be a credit card number. For instance, this happens on timestamp numbers in log files.
This PR adjusts the regex slightly so that one additional digit will be picked up if present; if so, that digit should throw off the algorithm and cause the number to not be redacted.
Ref: zd939528
@vkmita
=> Don't redact credit card numbers if immediately followed by additional digits

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
@ggrossman @vkmita 
This seemed like the most natural fix... if we really want up to 10 noise characters in between numbers we should probably specify them in a single group to prevent making the internet sad.
=> ZD#1045725 Make NUMBERS_WITH_LINE_NOISE checking a little less greedy/slow

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
Modify credit card redaction regex to detect the ascii code for the `+` character (`&#43;`).
/cc @zendesk/sustaining 
- https://support.zendesk.com/agent/tickets/1221399
- Low: Some numbers are incorrectly auto-redacted
=> Detect html code for + character

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
Fixes issue https://github.com/zendesk/credit_card_sanitizer/issues/25 by removing the semicolon from the acceptable line noise
/cc @zendesk/sustaining @ggrossman 
- Low: Some numbers are not correctly auto-redacted
=> Prevent HTML Entities from being captured as line noise

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
Removes `<` and `>` from the acceptable line noise so that credit card numbers will not be redacted through tags.
/cc @zendesk/sustaining @ggrossman 
- Low: Credit card numbers separated by angle brackets `<` or `>` are not redacted
=> Prevent numbers across html tags from being redacted

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
Fixes the encoding issues introduced by #23 
/cc @fneves @ggrossman @grosser
=> Force utf-8 encoding before scrubbing

.travis.yml, README.md, lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
Even with known credit card patterns and Luhn checksum, credit_card_sanitizer still sometimes has false positives and ends up redacting text that should not be redacted.
This PR improves the algorithm by having it pay attention to the groupings of a candidate card number.
Premise:
* A Visa card that appears in 4 groups of 4 digits e.g. 4111 1111 1111 1111 was probably a credit card number.
* A Visa card that appears as a single block of 16 digits, 4111111111111111, we can't tell and must treat it as a credit card number.
* But if a Visa card appears in a strange grouping such as 41 11 11 11 11 11 11 11, it probably is NOT a credit card number and we should avoid redacting it.
The table `CARD_NUMBER_GROUPINGS` contains a table of common groupings for the various card types supported.
We …
=> Examine card number groupings as a means of preventing false positives.

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
This moves the various settings (`replacement_token`, `expose_first`, etc.) into a settings hash, which can be passed in at `CreditCardSanitizer` construction time, but also can be passed on a per-call basis much like `Prop.throttle` in the [prop gem](https://github.com/zendesk/prop).
This will make it easier to turn settings on/off using, say, Arturo without having to construct a whole new `CreditCardSanitizer` object. Until now, the only way to alter the configuration of a `CreditCardSanitizer` was to make a new one.
Also: It's bugged me that the sanitizer is not thread-safe since it uses member variables like `@numbers` in the course of sanitization, so I changed it to use a `Candidate` class holding the original text and the string of digits. Probably a slight performance and memory …
=> Make it possible to change the configuration on a per-call basis

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
We have encountered instances of a number followed by whitespace followed by an IP address getting redacted, i.e. something of the form
4111 111.111.111.111
We believe that it is highly unusual for a credit card number to be separated by periods.
As such, to fix the above problem, we are removing . from the pattern for acceptable line noise between credit card digits.
/cc @kintner @jespr
=> Removes period (.) as a valid line noise character.

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
When sanitising HTML where the tag preceding a valid card number has an attribute such as a style attribute which contains a colon character, the card number is not sanitised. I have made a small change to the scheme regex to resolve this and have created a corresponding new test.
Feedback welcome.
=> Fixed bug when preceding html style attr has colon

Gemfile.lock, README.md, credit_card_sanitizer.gemspec, lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
The credit card sanitizer sometimes redacts shipping company tracking numbers, such as FedEx tracking numbers, as false positives for credit card numbers. If this happens, it can be a nuisance for customers who needed a tracking number out of a message but now find it blacked out.
This adds an option `exclude_tracking_numbers` to the sanitizer. If this option is on, a candidate number that is about to be redacted will be run through the [tracking_number](https://github.com/jkeen/tracking_number) gem to determine if it's a valid tracking number for some shipper. If it is, the number won't be redacted.
One of the challenges with this change was creating a test. We didn't want to use real FedEx tracking numbers. So, we generate random 15-digit numbers with a valid FedEx check digit and, by …
=> Don't redact credit card number candidates that are valid shipping tracking numbers

Gemfile.lock, credit_card_sanitizer.gemspec, lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
/cc @zendesk/secdev @ggrossman 
Bug 1: A long UPS number that starts with a valid credit card number that is 18 digits long
Fix: Increase the length of the match so that it will pick up numbers that will then fail the credit card specific checks.
Bug 2: A Shipping number that contains an & sign
Fix: And the & sign to the not allowed list.
* [low] small changes to avoid two specific edge cases
=> [SECDEV-1327] Fix two bugs numbers that contain & or a valid credit card number plus additional numbers

Rakefile, lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb, test/samples/html_example.html, test/samples/html_example_with_html.html, test/samples/html_example_with_line.html
/cc @zendesk/secdev @ggrossman 
Ticket https://support.zendesk.com/agent/tickets/2139072 pointed out that it is possible to use a number as a string class in an html tag and that if this is redacted we have a problem.
This code allows us to opt into the regular expression solution to not redact numbers within the html tags.
To test you will need to send in the option exclude_html_tags: true  
This gives us arturo control over this new redaction feature.
* JIRA: https://zendesk.atlassian.net/browse/SECDEV-1579
* [medium] will no longer redact credit card numbers inside <> with some letters in there.
=> [SECDEV-1579] add an option to exclude_html_tags from redaction

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
https://github.com/activemerchant/active_merchant/pull/1659
=> change credit card number regex for VISA to accept 19 digits

lib/credit_card_sanitizer.rb, scripts/generate_card.rb, test/credit_card_sanitizer_test.rb
@zendesk/secdev  @miketineo 
This is an alternative fix for #45
It looks like ARN numbers are matching due to an oversight in the discover regex where the anchor is only being applied to the first set of groupings. 
@ggrossman The anchor should apply to all the sets right? 
https://support.zendesk.com/agent/tickets/2818150
Low: valid discover credit card numbers aren't redacted.
=> [ZD#2818150] exclude arn numbers

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
Since 2017, Mastercard have a new series of BINs starting with 2: https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html
This change updates the `master` regex to support this range, similar to https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/credit_card_methods.rb#L7
z1: https://support.zendesk.com/agent/tickets/3223512
@zendesk/sustaining @zendesk/secdev
=> [ZD#3223512] Support Mastercard 2-series BINs

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
Since https://github.com/zendesk/credit_card_sanitizer/pull/43, strings of the form `<card_number><whitespace><expiration_date>` where `<expiration_date>` matches regex `EXPIRATION_DATE` result in the card number not being redacted. This is due to `without_expiration` wrapping `<whitespace><expiration_date>` (i.e. including leading whitespace) in a random string, which causes `valid_postfix?` to fail due to `!ALPHANUMERIC.match(postfix[0])`. As the postfix is not valid, redaction does not occur.
This change moves `<whitespace>` outside of the wrapping in `without_expiration`, so that `valid_postfix?` will subsequently succeed.
This also changes the bottom level `before` block in the tests to create a sanitizer with `parse_flanking: true`. This is due to tests on lines 188-201 which (it …
=> [ZD#3223512] Allow cards followed by whitespace + expiration to be redacted

lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
A bug was introduced in https://github.com/zendesk/credit_card_sanitizer/pull/49 where trailing whitespace was being discarded on expiration date matching. This change captures the trailing whitespace and retains it.
* z1: https://support.zendesk.com/agent/tickets/3223512
@zendesk/sustaining @zendesk/secdev @ggrossman
=> Fix whitespace being lost at end of matching group

README.md, lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
Add forward slash to the `SCHEME_OR_PLUS` pattern so that credit card-like numbers found within relative URLs are not redacted.
@zendesk-kevinramirez
=> Don't sanitize numeric sequences found within relative URLs

Gemfile.lock, README.md, credit_card_sanitizer.gemspec, lib/credit_card_sanitizer.rb, test/credit_card_sanitizer_test.rb
This adds a new option to the sanitizer, `return_changes`.
Currently, the `sanitize!` method behaves like `gsub!`:
* When changes are made, the updated string is returned. 
* When no changes are made, `nil` is returned.
When `return_changes` is `true`, the `sanitize!` method will instead return:
* When changes are made, an array of `[old_text, new_text]` containing the substitution that was made for each redacted credit card number.
* When no changes are made, `nil` is returned.
=> Add return_changes option

Gemfile, Gemfile.lock, Rakefile, credit_card_sanitizer.gemspec
Use a newer, more modern debugger.
We recommend adding the following configuration file `~/.rdbgrc`:
```
config set irb_console 1
config set use_short_path 1
```
This PR also removes unnecessary depencency `bump` and an unnecessary mention of `bundler` inside Gemfile.
=> Use debug instead of byebug
